-- ==============================================================
-- 1. Criação da Tabela de Trocas (RMA)
-- ==============================================================
CREATE TABLE IF NOT EXISTS public.exchanges (
    id bigint generated by default as identity primary key,
    wrong_item_id uuid references public.catalog_items(id) not null,
    correct_item_id uuid references public.catalog_items(id),
    quantity integer not null default 1,
    reason text not null,
    status text not null default 'pending',
    requested_at timestamp with time zone default now() not null,
    sent_at timestamp with time zone,
    received_at timestamp with time zone,
    notes text,
    photo_url text,
    created_by uuid, -- referenciando auth.users ou sua tabela de usuarios local se houver
    created_at timestamp with time zone default now() not null
);

-- ==============================================================
-- 2. Criação da Tabela do Diário de Fotos
-- ==============================================================
CREATE TABLE IF NOT EXISTS public.photo_diary (
    id uuid default gen_random_uuid() primary key,
    date date not null,
    technician_id uuid references public.people(id) not null,
    description text not null,
    location text,
    photos text[] default '{}',
    created_by uuid,
    created_at timestamp with time zone default now() not null
);

-- Habilitar RLS (Row Level Security) se necessário (aqui ajustado para full access no desenvolvimento)
ALTER TABLE public.exchanges ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.photo_diary ENABLE ROW LEVEL SECURITY;

-- Políticas de acesso livre para insert/select/update/delete (para MVP)
CREATE POLICY "Public full access exchanges" ON public.exchanges FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public full access photo_diary" ON public.photo_diary FOR ALL USING (true) WITH CHECK (true);

-- ==============================================================
-- 3. Criação do Storage (Bucket) para as Fotos
-- ==============================================================
-- A query abaixo criará o bucket se ele não existir
INSERT INTO storage.buckets (id, name, public) 
VALUES ('photos', 'photos', true)
ON CONFLICT (id) DO NOTHING;

-- Policies do Storage para permitir upload/download
CREATE POLICY "Public Access Storage" ON storage.objects FOR SELECT USING (bucket_id = 'photos');
CREATE POLICY "Public Insert Storage" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'photos');
CREATE POLICY "Public Update Storage" ON storage.objects FOR UPDATE USING (bucket_id = 'photos');
CREATE POLICY "Public Delete Storage" ON storage.objects FOR DELETE USING (bucket_id = 'photos');
