-- 1. ADICIONA A COLUNA DE VALOR TOTAL LIVRE (para corrigir centavos da Nota Fiscal)
ALTER TABLE public.catalog_items ADD COLUMN IF NOT EXISTS total_price numeric(10,2);

-- 2. CALCULA O QUE JÁ EXISTE NO BANCO E ESTAVA SEM VALOR TOTAL
UPDATE public.catalog_items SET total_price = quantity_purchased * unit_price WHERE total_price IS NULL;

-- 3. CORRIGE O VALOR EXATO DOS PRODUTOS DAQUELA PLANILHA (para bater os centavos rigorosamente)
UPDATE public.catalog_items SET total_price = 62.58 WHERE name = 'Fita Isolante Preta com medida de 20mx19mm';
UPDATE public.catalog_items SET total_price = 18.87 WHERE name = 'Fita Abraçadeira feito a partir de Nylon 6.6 155mmx3,6mm';
UPDATE public.catalog_items SET total_price = 59.21 WHERE name = 'Porca Gaiola 9,05mmx12,45mm M5';
UPDATE public.catalog_items SET total_price = 107.18 WHERE name = 'Parafuso Philips 4,5mmx19,1mm M5';
UPDATE public.catalog_items SET total_price = 227.36 WHERE name = 'Parafuso Fenda Cruzada cabeça chata 5mmx60mm';
UPDATE public.catalog_items SET total_price = 231.28 WHERE name = 'Parafuso Sextavado do tipo Soberba 1/4"x65mm';
UPDATE public.catalog_items SET total_price = 875.53 WHERE name = 'Parafuso com Cabeça do tipo lentilha 1/4x1/2';
UPDATE public.catalog_items SET total_price = 148.42 WHERE name = 'Arruela Simples 1/4';
UPDATE public.catalog_items SET total_price = 148.42 WHERE name = 'Porca sextavada 1/4';
UPDATE public.catalog_items SET total_price = 873.60 WHERE name = 'Porca Losangular Rosca de 1/4';
UPDATE public.catalog_items SET total_price = 503.09 WHERE name = 'Bucha de expansão do tipo UX plástica 8mmx50mm';
UPDATE public.catalog_items SET total_price = 502.01 WHERE name = 'Bucha de expansão do tipo UX plástica 10mmx60mm';
UPDATE public.catalog_items SET total_price = 125.93 WHERE name = 'Bucha de Nylon com abas para painéis/DryWall 4,5mmx15mm';
UPDATE public.catalog_items SET total_price = 372.68 WHERE name = 'Eletrocalha chapa CH 22 50mmx50mmx3m';
UPDATE public.catalog_items SET total_price = 12.26 WHERE name = 'Curva Horizontal 90° chapa CH 22 com 90° 50mmx50mm';
UPDATE public.catalog_items SET total_price = 13029.30 WHERE name = 'Perfilado Galvanizado à fogo no perfil C 38x38x6000mm';
UPDATE public.catalog_items SET total_price = 22.75 WHERE name = 'Junção Interna em T Galvanizada do tipo perfurado com 38x38mm';
UPDATE public.catalog_items SET total_price = 489.40 WHERE name = 'Curva Horizontal de 90° Galvanizada para Perfilado de 38x38mm';
UPDATE public.catalog_items SET total_price = 2768.37 WHERE name = 'Mão Francesa Simples chapa CH 20 38x38x150mm';
UPDATE public.catalog_items SET total_price = 1704.53 WHERE name = 'Tala Reta chapa CH 18 ou CH 20 100mmx50mm';
UPDATE public.catalog_items SET total_price = 674.90 WHERE name = 'Tala Reta para Perfilado de 38x38mm 4(Quatro) furos';
UPDATE public.catalog_items SET total_price = 29.47 WHERE name = 'Saída Lateral Horizontal para eletroduto 1';
UPDATE public.catalog_items SET total_price = 3697.40 WHERE name = 'Saída Lateral Horizontal Perfilado para Eletroduto 1';
UPDATE public.catalog_items SET total_price = 36.12 WHERE name = 'Saída Lateral Horizontal p/ Perfilado 38x38mm';
UPDATE public.catalog_items SET total_price = 997.50 WHERE name = 'Box Reto com rosca, liga de alumínio Silício 1';
UPDATE public.catalog_items SET total_price = 144.65 WHERE name = 'Eletroduto Flexível Metálico Revestido de PVC 1';
UPDATE public.catalog_items SET total_price = 1117.80 WHERE name = 'Eletroduto do tipo rígido com rosca 1x3m';
UPDATE public.catalog_items SET total_price = 1175.57 WHERE name = 'Eletroduto do tipo rígido sem rosca PVC e de cor cinza 1x3m';
UPDATE public.catalog_items SET total_price = 117.26 WHERE name = 'Curva do tipo rígido com rosca aço galvanizado 1';
UPDATE public.catalog_items SET total_price = 782.34 WHERE name = 'Curva do tipo rígido sem rosca PVC e de cor cinza 1';
UPDATE public.catalog_items SET total_price = 44.41 WHERE name = 'Luva de Ligação do tipo rígido com rosca aço galvanizado 1';
UPDATE public.catalog_items SET total_price = 743.76 WHERE name = 'Luva de Ligação tipo rígido sem rosca PVC e de cor cinza 1';
UPDATE public.catalog_items SET total_price = 33.26 WHERE name = 'Abraçadeira do tipo “D", aço galvanizado, com parafuso 1';
UPDATE public.catalog_items SET total_price = 199.83 WHERE name = 'Abraçadeira do tipo “D" PVC e de cor cinza 1';
UPDATE public.catalog_items SET total_price = 485.94 WHERE name = 'Conector com rosca, para condulete múltiplo, alumínio 1';
UPDATE public.catalog_items SET total_price = 529.04 WHERE name = 'Conector para condulete múltiplo PVC sem rosca, cor cinza 1';
UPDATE public.catalog_items SET total_price = 315.25 WHERE name = 'Condulete do tipo múltiplo X, com rosca alumínio';
UPDATE public.catalog_items SET total_price = 1987.52 WHERE name = 'Condulete do tipo múltiplo X, PVC cor cinza';
UPDATE public.catalog_items SET total_price = 133.05 WHERE name = 'Tampa de alumínio para Condulete, do tipo cega';
UPDATE public.catalog_items SET total_price = 2146.20 WHERE name = 'Tampa de PVC para Condulete, cor cinza e de 3 postos RJ45 fêmea';
UPDATE public.catalog_items SET total_price = 455.66 WHERE name = 'Tampa p/ Condulete fabricado em PVC, ser do tipo cega e de cor cinza';
UPDATE public.catalog_items SET total_price = 2152.14 WHERE name = 'Módulo Tomada para RJ45 fêmea Cat.6 da cor branca';
UPDATE public.catalog_items SET total_price = 170.82 WHERE name = 'Módulo Tomada do tipo Cega da cor branca';
UPDATE public.catalog_items SET total_price = 3593.16 WHERE name = 'Conector RJ 45 Fêmea keystone do tipo RJ-45, UTP, Cat.6 tipo IDC';
UPDATE public.catalog_items SET total_price = 106.91 WHERE name = 'Conector RJ 45 Macho para cabo UTP';
UPDATE public.catalog_items SET total_price = 582.40 WHERE name = 'Abraçadeira Velcro de Nylon e Poliéster com medida de 3m';
UPDATE public.catalog_items SET total_price = 1783.60 WHERE name = 'Rack fabricado 19x16U';
UPDATE public.catalog_items SET total_price = 3494.40 WHERE name = 'Rack fabricado 19x12U';
UPDATE public.catalog_items SET total_price = 1461.60 WHERE name = 'Patch Panel Multilan Cat.6 terminal 110 IDC 19x1U';
UPDATE public.catalog_items SET total_price = 805.00 WHERE name = 'Guia de Cabo 9x1U';
UPDATE public.catalog_items SET total_price = 929.60 WHERE name = 'Bandeja Frontal 19x1U';
UPDATE public.catalog_items SET total_price = 873.60 WHERE name = 'Régua para rack 8 tomadas tomadas tripolar 2P+T de 10 A 19x1U';
UPDATE public.catalog_items SET total_price = 1897.00 WHERE name = 'Distribuidor Interno Óptico 12 FO com 19 tipo gaveta';
UPDATE public.catalog_items SET total_price = 2.88 WHERE name = 'Conector Fast para fibras Monomodo, padrão SC/APC ou SC/UPC';
UPDATE public.catalog_items SET total_price = 1.32 WHERE name = 'Acoplador Passante padrão SC UPC com abas e do tipo Simplex';
UPDATE public.catalog_items SET total_price = 291.20 WHERE name = 'Cordão Óptico do tipo Mono Modo Simplex, tipo LC/UPC-SC/UPC 1-2 metros';
UPDATE public.catalog_items SET total_price = 1668.38 WHERE name = 'Módulo Transceiver SFP, Monomodo Simplex, padrão LC';
UPDATE public.catalog_items SET total_price = 31684.80 WHERE name = 'Cabo de transmissão de dados categoria CAT.6 305 metros';
UPDATE public.catalog_items SET total_price = 2226.00 WHERE name = 'Cabo de fibra óptica Mini Flat Drop, Monomodo, 500 metros 2F.O.';
UPDATE public.catalog_items SET total_price = 4515.00 WHERE name = 'Patch Cord CAT.6 UTP, CMX, Certificado ANATEL RJ45, de cor azul 2,5m';
UPDATE public.catalog_items SET total_price = 14.00 WHERE name = 'Disco Abrasivo de corte 115mm x 22,22mm';
UPDATE public.catalog_items SET total_price = 21.00 WHERE name = 'Broca para alvenaria SDS Plus 8mm x 210mm';
UPDATE public.catalog_items SET total_price = 264.60 WHERE name = 'Fita para Etiquetadora PT-80 MK-231 12mmx0.47';
UPDATE public.catalog_items SET total_price = 4.54 WHERE name = 'Esticador Plástico tipo Cunha para fibra drop';
UPDATE public.catalog_items SET total_price = 30.80 WHERE name = 'Alça Preformada para Cabos de Fibra Óptica';
UPDATE public.catalog_items SET total_price = 16.52 WHERE name = 'Parafuso do tipo Gancho zincado para bucha de 10mm';
UPDATE public.catalog_items SET total_price = 38548.50 WHERE name = 'Access Point Indoor U6+, Unifi';
UPDATE public.catalog_items SET total_price = 4348.50 WHERE name = 'Firewall Físico UDM-PRO-BR, Unifi';
UPDATE public.catalog_items SET total_price = 38388.00 WHERE name = 'Switch 24 Port. PoE, Ger. USW-24-PoE-BR, Unifi';
UPDATE public.catalog_items SET total_price = 2848.50 WHERE name = 'Switch 24 Port. Ger, 2 SFP USW-24-BR, Unifi';
UPDATE public.catalog_items SET total_price = 1423.50 WHERE name = 'Switch 8 Port. SFP+ Unifi';
UPDATE public.catalog_items SET total_price = 178.50 WHERE name = 'Cabo Dac - UACC-DAC-SFP10-0.5m';
UPDATE public.catalog_items SET total_price = 517.50 WHERE name = 'Adaptador PoE (Ejetor) 15W 100-240 CA 60Hz';
